<a href="https://colab.research.google.com/github/Kavya-K-S/DAUP/blob/main/Module4_practiceQuestions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Create a numpy array filled with all ones by defining its shape.
import numpy as np
arr = np.ones((3, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#2. How do you remove rows from a Numpy array that contains non-numeric values?
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, "x", 6],
    [7, 8, 9],
    ["a", 11, 12]
], dtype=object)

mask = []
for row in arr:
    try:
        [float(x) for x in row]
        mask.append(True)
    except ValueError:
        mask.append(False)

clean_arr = arr[mask].astype(float)
print(clean_arr)


array(['1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [5]:
#3. Remove single-dimensional entries from the shape of an array
import numpy as np

arr = np.array([[[1], [2], [3]]])  # Shape (1, 3, 1)
print("Original shape:", arr.shape)

squeezed = np.squeeze(arr)
print("After squeeze shape:", squeezed.shape)
print(squeezed)

Original shape: (1, 3, 1)
After squeeze shape: (3,)
[1 2 3]


In [6]:
#4. How do you check whether specified values are present in the NumPy array?
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

check = np.isin([20, 60], arr)
print(check)

[ True False]


In [7]:
#Write a NumPy program to sort a given array of shape 2 along the first axis, last axis, and flattened array.
import numpy as np

arr = np.array([[30, 10, 20],
                [60, 40, 50]])

print("Original Array:\n", arr)
sorted_axis0 = np.sort(arr, axis=0)
print("\nSorted along first axis (axis=0):\n", sorted_axis0)
sorted_axis1 = np.sort(arr, axis=-1)
print("\nSorted along last axis (axis=-1):\n", sorted_axis1)
sorted_flat = np.sort(arr, axis=None)
print("\nSorted flattened array:\n", sorted_flat)


Original Array:
 [[30 10 20]
 [60 40 50]]

Sorted along first axis (axis=0):
 [[30 10 20]
 [60 40 50]]

Sorted along last axis (axis=-1):
 [[10 20 30]
 [40 50 60]]

Sorted flattened array:
 [10 20 30 40 50 60]


In [8]:
# 6. Write a NumPy program to create a structured array from a given student name, height,class, and data type. Now sort by class, then height if the classes are equal.
students = np.array([('Alice', 5.5, 10),
                     ('Bob', 6.0, 9),
                     ('Charlie', 5.8, 10),
                     ('David', 5.9, 9)],
                    dtype=[('name', 'U10'), ('height', 'f4'), ('class', 'i4')])
sorted_students = np.sort(students, order=['class', 'height'])
print(sorted_students)


[('David', 5.9,  9) ('Bob', 6. ,  9) ('Alice', 5.5, 10)
 ('Charlie', 5.8, 10)]


In [9]:
# 7. Write a NumPy program to sort a given complex array using the real part first, then theimaginary part.
complex_arr = np.array([2 + 3j, 1 + 7j, 2 + 1j, 1 + 2j])
sorted_complex = np.sort_complex(complex_arr)
print(sorted_complex)

[1.+2.j 1.+7.j 2.+1.j 2.+3.j]


In [10]:
# 8. Write a NumPy program to sort a given array by the nth column.
arr = np.array([[10, 2, 5],
                [3, 7, 1],
                [8, 6, 4]])
n = 1
sorted_by_col = arr[arr[:, n].argsort()]
print(sorted_by_col)


[[10  2  5]
 [ 8  6  4]
 [ 3  7  1]]


In [11]:
# 9. Calculate the sum of the diagonal elements of a NumPy array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
diag_sum = np.trace(arr2)
print(diag_sum)

15


In [12]:
# 10. Write a program for Matrix Multiplication in NumPy
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
C = np.matmul(A, B)
print(C)

[[19 22]
 [43 50]]


In [13]:
# 11. Multiply matrices of complex numbers using NumPy in Python
A = np.array([[1+2j, 2+3j],
              [3+4j, 4+5j]])
B = np.array([[5+6j, 6+7j],
              [7+8j, 8+9j]])
C = np.matmul(A, B)
print(C)

[[-17. +53.j -19. +61.j]
 [-21.+105.j -23.+121.j]]


In [14]:
# 12. Compute the covariance matrix of two given NumPy arrays.
x = np.array([2.1, 2.5, 3.6, 4.0])
y = np.array([8, 10, 12, 14])
cov_matrix = np.cov(x, y)
print(cov_matrix)

[[0.80333333 2.26666667]
 [2.26666667 6.66666667]]


In [15]:
# 13. Convert covariance matrix to correlation matrix using Python
corr_matrix = np.corrcoef(x, y)
print(corr_matrix)


[[1.         0.97945704]
 [0.97945704 1.        ]]


In [16]:
# 14. Write a NumPy program to compute the histogram of nums against the bins.
nums = np.array([0, 1, 2, 1, 1, 4, 5, 6, 2, 3, 1])
hist, bins = np.histogram(nums, bins=[0, 1, 2, 3, 4, 5, 6])
print(hist)
print(bins)

[1 4 2 1 1 2]
[0 1 2 3 4 5 6]


In [17]:
# 15. Write a NumPy program to compute the cross-correlation of two given arrays
a = np.array([1, 2, 3])
b = np.array([0, 1, 0.5])
cross_corr = np.correlate(a, b, mode="full")
print(cross_corr)

[0.5 2.  3.5 3.  0. ]


In [18]:
# 16. Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
mean = np.mean(arr, axis=1)
std = np.std(arr, axis=1)
var = np.var(arr, axis=1)
print(mean)
print(std)
print(var)

[2. 5. 8.]
[0.81649658 0.81649658 0.81649658]
[0.66666667 0.66666667 0.66666667]
