<a href="https://colab.research.google.com/github/Kavya-K-S/DAUP/blob/main/module3_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

*   Numerical python
*   python library for working with array
*   50x faster than python lists


In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


ndarray


In [5]:
type(a)

numpy.ndarray

MULTIDIMENIONAL ARRAY

In [11]:
import numpy as np
a=np.array(5)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print("Dimension=",a.ndim)
print(b)
print("Dimension=",b.ndim)
print(c)
print("Dimension=",c.ndim)
print(x)
print("Dimension=",x.ndim)

5
Dimension= 0
[1 2 3 4 5]
Dimension= 1
[[1 2 3]
 [4 5 6]]
Dimension= 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension= 3


In [14]:
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]
[[1 2 3]]


INDEXING

In [15]:
x=np.array([11,12,13,14,15,60,70,80,90,100])
print(x)
z=x[np.array([3,3,1,8])]
print(z)

[ 11  12  13  14  15  60  70  80  90 100]
[14 14 12 90]


In [21]:
d=[1,2,3,4,5]
e=[5,6,7,8,9]
f=[2,45,32,78,65]
g=[3,6,8,9,2]
h=[66,99,88,33,22]
my_matrice=np.matrix([d,e,f,g,h])
my_matrice
type(my_matrice)

numpy.matrix

In [22]:
my_matrice[1:4,2:] #rows 1 to 3 and columns 2 to 4

matrix([[ 7,  8,  9],
        [32, 78, 65],
        [ 8,  9,  2]])

In [20]:
my_matrice[2:5,1:3]

matrix([[45, 32],
        [ 6,  8],
        [99, 88]])

In [29]:
l=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(l)
print("list=",l)
print("array\n",a)
print(type(l))
print(type(a))

list= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'list'>
<class 'numpy.ndarray'>
