<a href="https://colab.research.google.com/github/Kavya-K-S/DAUP/blob/main/module3_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

*   Numerical python
*   python library for working with array
*   50x faster than python lists


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


ndarray


In [ ]:
type(a)

numpy.ndarray

MULTIDIMENIONAL ARRAY

In [ ]:
import numpy as np
a=np.array(5)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print("Dimension=",a.ndim)
print(b)
print("Dimension=",b.ndim)
print(c)
print("Dimension=",c.ndim)
print(x)
print("Dimension=",x.ndim)

5
Dimension= 0
[1 2 3 4 5]
Dimension= 1
[[1 2 3]
 [4 5 6]]
Dimension= 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension= 3


In [ ]:
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]
[[1 2 3]]


INDEXING

In [ ]:
x=np.array([11,12,13,14,15,60,70,80,90,100])
print(x)
z=x[np.array([3,3,1,8])]
print(z)

[ 11  12  13  14  15  60  70  80  90 100]
[14 14 12 90]


In [ ]:
d=[1,2,3,4,5]
e=[5,6,7,8,9]
f=[2,45,32,78,65]
g=[3,6,8,9,2]
h=[66,99,88,33,22]
my_matrice=np.matrix([d,e,f,g,h])
my_matrice
type(my_matrice)

numpy.matrix

In [ ]:
my_matrice[1:4,2:] #rows 1 to 3 and columns 2 to 4

matrix([[ 7,  8,  9],
        [32, 78, 65],
        [ 8,  9,  2]])

In [ ]:
my_matrice[2:5,1:3]

matrix([[45, 32],
        [ 6,  8],
        [99, 88]])

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(l)
print("list=",l)
print("array\n",a)
print(type(l))
print(type(a))

list= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
k=np.array([1,2,3,4,5,6,])
copy1_=k.copy()
view1_=k.view()
print(k)
print(copy1_)
print(view1_)
k[2]=90
print("After changing the value",view1_)
print("copied array=",copy1_)
print("viewed arra=",view1_)


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
After changing the value [ 1  2 90  4  5  6]
copied array= [1 2 3 4 5 6]
viewed arra= [ 1  2 90  4  5  6]


RESHAPE

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
newarr=arr.reshape(2,2,3)
print(newarr)

(12,)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


ARANGE FUNCTION

In [ ]:
print(np.arange(10))
print(np.arange(5,10))
print(np.arange(5,10,0.5))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


LINSPACE
return evenly spaced numbers over a specified interval

In [ ]:
x=np.linspace(0,6,9)
x

array([0.  , 0.75, 1.5 , 2.25, 3.  , 3.75, 4.5 , 5.25, 6.  ])

Row or Column sum and mean

In [3]:
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(x.sum(axis=0))
print(x.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


Zeroes ,Ones and empty

np.zeros-> initializes the values of a matrix to 0

np.ones->initializes the values of a matrix to 0

np.empty->initializes the values of a matrix to some random values

In [5]:
x=np.zeros((2,2))
print(x)
y=np.ones((2,2))
print(y)
z=np.empty((2,3))
print(z)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5.04741003e-315 0.00000000e+000 6.55430404e-310]
 [4.85721075e-317 6.55428310e-310 6.55428310e-310]]


LISTS, TUPLES TO NUMPY

In [7]:
l=[1,2,3]
print(type(l))
t=(1,2,3)
print(type(t))
a=np.asarray(l)
print(type(a))
b=np.asarray(t)
print(type(b))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


HOW CAN WE JOIN TWO ARRAYS? CONCATENATION

In [10]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[41,51,61],[7,8,9]])
arr=np.concatenate((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [41 51 61]
 [ 7  8  9]]


hstack VS vstack


hstack can append data horizontally

vstck can append data vertically

In [11]:
a=np.array([21,22,23])
b=np.array([98,23,34])
s=np.hstack((a,b))
print(s)
s=np.vstack((a,b))
print(s)

[21 22 23 98 23 34]
[[21 22 23]
 [98 23 34]]


In [17]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,5)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [20]:
arr=np.array(['a','b','c','d','e','f','g'])
print(type(arr))

<class 'numpy.ndarray'>


where True yield x , otherwise yield y

In [24]:
arr=np.array([1,2,3,4,5,4,2,4])
x=np.where(arr==4)
print(x,type(x))

(array([3, 5, 7]),) <class 'tuple'>


In [26]:
a=np.arange(10)
np.where(a<5,a,a*10) #if a<5 then print a else print a*10


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

SORTING

In [28]:
print(np.sort(arr))

[1 2 2 3 4 4 4 5]


In [29]:
a=np.array(['apple','cherry','banana','guava','blueberry'])
np.sort(a)

array(['apple', 'banana', 'blueberry', 'cherry', 'guava'], dtype='<U9')